"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class dspl_t(object):
    __slots__ = ["utime", "port", "address", "enabled", "channelMode", "lightLevel"]

    __typenames__ = ["int64_t", "string", "string", "boolean", "int32_t", "int32_t"]

    __dimensions__ = [None, None, None, None, None, None]

    def __init__(self):
        self.utime = 0
        self.port = ""
        self.address = ""
        self.enabled = False
        self.channelMode = 0
        self.lightLevel = 0

    def encode(self):
        buf = BytesIO()
        buf.write(dspl_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        __port_encoded = self.port.encode('utf-8')
        buf.write(struct.pack('>I', len(__port_encoded)+1))
        buf.write(__port_encoded)
        buf.write(b"\0")
        __address_encoded = self.address.encode('utf-8')
        buf.write(struct.pack('>I', len(__address_encoded)+1))
        buf.write(__address_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">bii", self.enabled, self.channelMode, self.lightLevel))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != dspl_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return dspl_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = dspl_t()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        __port_len = struct.unpack('>I', buf.read(4))[0]
        self.port = buf.read(__port_len)[:-1].decode('utf-8', 'replace')
        __address_len = struct.unpack('>I', buf.read(4))[0]
        self.address = buf.read(__address_len)[:-1].decode('utf-8', 'replace')
        self.enabled = bool(struct.unpack('b', buf.read(1))[0])
        self.channelMode, self.lightLevel = struct.unpack(">ii", buf.read(8))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if dspl_t in parents: return 0
        tmphash = (0xa4a60fcafbdf8991) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if dspl_t._packed_fingerprint is None:
            dspl_t._packed_fingerprint = struct.pack(">Q", dspl_t._get_hash_recursive([]))
        return dspl_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", dspl_t._get_packed_fingerprint())[0]

