"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class switch_t(object):
    __slots__ = ["utime", "channel", "state", "label"]

    __typenames__ = ["int64_t", "int8_t", "int8_t", "string"]

    __dimensions__ = [None, None, None, None]

    def __init__(self):
        self.utime = 0
        self.channel = 0
        self.state = 0
        self.label = ""

    def encode(self):
        buf = BytesIO()
        buf.write(switch_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qbb", self.utime, self.channel, self.state))
        __label_encoded = self.label.encode('utf-8')
        buf.write(struct.pack('>I', len(__label_encoded)+1))
        buf.write(__label_encoded)
        buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != switch_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return switch_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = switch_t()
        self.utime, self.channel, self.state = struct.unpack(">qbb", buf.read(10))
        __label_len = struct.unpack('>I', buf.read(4))[0]
        self.label = buf.read(__label_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if switch_t in parents: return 0
        tmphash = (0x1e875f75e6c0a4da) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if switch_t._packed_fingerprint is None:
            switch_t._packed_fingerprint = struct.pack(">Q", switch_t._get_hash_recursive([]))
        return switch_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", switch_t._get_packed_fingerprint())[0]

