"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class bytes_t(object):
    __slots__ = ["utime", "length", "data"]

    __typenames__ = ["int64_t", "int32_t", "byte"]

    __dimensions__ = [None, None, ["length"]]

    def __init__(self):
        self.utime = 0
        self.length = 0
        self.data = b""

    def encode(self):
        buf = BytesIO()
        buf.write(bytes_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.utime, self.length))
        buf.write(bytearray(self.data[:self.length]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != bytes_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return bytes_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = bytes_t()
        self.utime, self.length = struct.unpack(">qi", buf.read(12))
        self.data = buf.read(self.length)
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if bytes_t in parents: return 0
        tmphash = (0x182b8da2dc0260c7) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if bytes_t._packed_fingerprint is None:
            bytes_t._packed_fingerprint = struct.pack(">Q", bytes_t._get_hash_recursive([]))
        return bytes_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", bytes_t._get_packed_fingerprint())[0]

